# Setup
title:               Lazy Loading AB
tagline:             ''
description:         'Lazy Loading AB'
url:                 https://www.lazyloading.se
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Erik Pettersson
  url:               https://www.lazyloading.se
  email:             erik@lazyloading.se

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
